### ISSUE TITLE
I can't install this userscript.

### ISSUE THREAD

**Issue by YhlasY** [renzhamin/codeforces-helper#1]
I installed Tampermonkey to my edge. When I click the link to install this userscript just blue line appear  at the top and nothing happen then.

**Comment by renzhamin** [comment]
Not sure whats causing that problem, could be  adblocker or something but a quick workaround would be,

Click on the tampermonkey icon and create new script then copy paste the contents of the [userscript](https://github.com/renzhamin/codeforces-helper/blob/main/main.user.js)

**Comment by YhlasY** [comment]
It works now, thanks for this userscript Sent from Mail for Windows From: Tasnim FerdousSent: Thursday, April 27, 2023 4:36 AMTo: renzhamin/codeforces-helperCc: YhlasY; AuthorSubject: Re: [renzhamin/codeforces-helper] I can't install this userscript. (Issue #1) Not sure whats causing that problem, could be adblocker or something but a quick workaround would be,Click on the tampermonkey icon and create new script then copy paste the contents of the userscript—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
